server:
    tty: true
    stdin_open: true
    build: ./server
    volumes:
        - ./volumes/logs:/logs
        - ./server/app:/app/
        - ./server/vendor/greenhouse2:/vendor/greenhouse2
        - ./server/vendor/datahog2:/vendor/datahog2
        - ./server/vendor/databacon2:/vendor/databacon2
    links:
        - db:db
    ports:
      - 8080:80

db:
    build: ./db
    command: /bin/sh /start
    ports:
      - 5432:5432
